/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MakingChaiRouteImport } from './routes/making-chai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProuductPidRouteImport } from './routes/Prouduct.$pid'

const ProductsLazyRouteImport = createFileRoute('/Products')()

const ProductsLazyRoute = ProductsLazyRouteImport.update({
  id: '/Products',
  path: '/Products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Products.lazy').then((d) => d.Route))
const MakingChaiRoute = MakingChaiRouteImport.update({
  id: '/making-chai',
  path: '/making-chai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProuductPidRoute = ProuductPidRouteImport.update({
  id: '/Prouduct/$pid',
  path: '/Prouduct/$pid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/making-chai': typeof MakingChaiRoute
  '/Products': typeof ProductsLazyRoute
  '/Prouduct/$pid': typeof ProuductPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/making-chai': typeof MakingChaiRoute
  '/Products': typeof ProductsLazyRoute
  '/Prouduct/$pid': typeof ProuductPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/making-chai': typeof MakingChaiRoute
  '/Products': typeof ProductsLazyRoute
  '/Prouduct/$pid': typeof ProuductPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/making-chai' | '/Products' | '/Prouduct/$pid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/making-chai' | '/Products' | '/Prouduct/$pid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/making-chai'
    | '/Products'
    | '/Prouduct/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MakingChaiRoute: typeof MakingChaiRoute
  ProductsLazyRoute: typeof ProductsLazyRoute
  ProuductPidRoute: typeof ProuductPidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Products': {
      id: '/Products'
      path: '/Products'
      fullPath: '/Products'
      preLoaderRoute: typeof ProductsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/making-chai': {
      id: '/making-chai'
      path: '/making-chai'
      fullPath: '/making-chai'
      preLoaderRoute: typeof MakingChaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Prouduct/$pid': {
      id: '/Prouduct/$pid'
      path: '/Prouduct/$pid'
      fullPath: '/Prouduct/$pid'
      preLoaderRoute: typeof ProuductPidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MakingChaiRoute: MakingChaiRoute,
  ProductsLazyRoute: ProductsLazyRoute,
  ProuductPidRoute: ProuductPidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
